# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



# Site settings
title: Garry's Portfolio
email: garryfung@u.nus.edu
description: Welcome! This online portfolio is a pet project of mine during the Covid-19 circuit breaker period, experimenting with web development and UI/UX topics.
# When Local Host
$baseurl: ""
# When push to Git
baseurl: "https://leoxovi.github.io/"

# Team names, titles and social links
people:
- name: Garry Fung
  pic: 0
  position: Project Engineer
  social:
    - title: linkedin
      url: "http://linkedin.com/garryfung"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: "https://twitter.com/leoxovi"
  - title: facebook
    url: "https://www.facebook.com/leoxovi/"
  - title: stack-overflow
    url: "https://stackoverflow.com/users/6132371/leoxovi"
  - title: bitbucket
    url: "http://github.com/leoxovi"
  - title: github
    url: "http://github.com/leoxovi"

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
