# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Garry's Portfolio
email: garryfung@u.nus.edu
description: Electrical Engineer, Software Developer and Deep Learning Enthusiast. Welcome to my Digital Portfolio! This online portfolio was made during the Covid-19 Circuit Breaker period in Singapore when I was experimenting with front-end web development and UI/UX.
# When Local Host
baseurl: ""
# When push to Git
# baseurl: "https://leoxovi.github.io/"

# Team names, titles and social links
people:
  - name: Garry Fungs
    pic: 0
    position: Project Engineer
    social:
      - title: linkedin
        url: "http://linkedin.com/garryfung"

    # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: "https://twitter.com/leoxovi"
  - title: facebook
    url: "https://www.facebook.com/leoxovi/"
  - title: stack-overflow
    url: "https://stackoverflow.com/users/6132371/leoxovi"
  - title: bitbucket
    url: "http://github.com/leoxovi"
  - title: github
    url: "http://github.com/leoxovi"
  - title: linkedin
    url: "http://linkedin.com/garryfung"

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 94a1ed
  secondary: 94a1ed
  secondary-dark: 333
  muted: 777

# Font Families
font:
  primary: 'Montserrat, "Helvetica Neue",Helvetica,Arial,sans-serif'
  secondary: '"Droid Serif", "Helvetica Neue", Helvetica,Arial,sans-serif'
